---
steps:
  - label: ':debian: arm64: Build & Package'
    command: ".buildkite/build.sh"
    agents:
      queue: "default_arm64"
    artifact_paths:
      - "build-focal/*"

  - label: ':debian: amd64: Build & Package'
    command: ".buildkite/build.sh"
    agents:
      queue: "default"
    artifact_paths:
      - "build-focal/*"

  - block: "Release?"
    prompt: "Release to archive?"

  - label: ':debian: Publish debs'
    command:
      - >
        aptly-upload
        --aptly-url https://apt-repo.kx.gd
        --retries 3
        --repo kx-builds-focal
        --series focal
        build-focal/*.deb
    retry:
      automatic: true
    plugins:
      artifacts#v1.2.0:
        download: "build-focal/*.deb"
      docker#v1.4.0:
        image: "${ECR}/ci-tools"
        always-pull: true
        workdir: /src
        environment:
          - APTLY_UNAME
          - APTLY_PASSWD
